name: CI/CD Frontend Docker

on:
  push:
    branches:
      - develop
      - main

env:
  IMAGE: erikadias/fatec-frontend
  TAG: latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Smoke-test container (1 CPU, 1 GiB RAM)
        run: |
          docker run --rm -d --name smoke \
            -p 8080:80 \
            --cpus="1.0" \
            --memory="1g" \
            ${{ env.IMAGE }}:${{ env.TAG }}
          # aguarda o nginx subir
          sleep 5
          curl --fail http://localhost:8080 || (docker logs smoke && exit 1)
          docker stop smoke
