# CI Frontend (Windows Runner)
name: CI Frontend
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-tests:
    name: Testes Unitários
    runs-on: windows-latest           # Usa runner Windows para Node.js
    steps:
      - name: Checkout do código       # Faz o checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js            # Configura a versão do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências    # Instala pacotes via npm
        run: npm ci

      - name: Executar testes unitários  # Executa os testes unitários
        run: npm test

  integration-tests:
    name: Testes de Integração
    runs-on: windows-latest           # Usa runner Windows para Node.js
    steps:
      - name: Checkout do código         # Faz o checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js              # Configura a versão do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências      # Instala pacotes via npm
        run: npm ci

      - name: Executar testes de integração  # Roda testes de integração (ajuste comando conforme setup)
        run: npm run test:integration
